# Generated by Django 3.1 on 2022-11-12 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='active',
            new_name='is_active',
        ),
    ]
